friendcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('about/', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('friends/', views.friends_index, name='friends_index'),
  path('friends/<int:friend_id>/', views.friends_detail, name='friends_detail'),
  path('friends/create/', views.FriendCreate.as_view(), name='friends_create'),
  path('friends/update/', views.FriendUpdate.as_view(), name='friends_update'),
  path('friends/delete/', views.FriendDelete.as_view(), name='friends_delete'),
  path('friends/<int:friend_id>/add_order/', views.add_order, name='add_order'),
  path('items/create/', views.ItemCreate.as_view(), name='items_create'),
  path('items/<int:pk>/', views.ItemDetail.as_view(), name='items_detail'),
  path('items/', views.ItemList.as_view(), name='items_index'),
  path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name='items_update'),
  path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='items_delete'),
  path('friends/<int:friend_id>/assoc_item/<int:item_id>/', views.assoc_item, name='assoc_item'),
  path('', views.Home.as_view(), name='home'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from ast import FloorDiv
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

DRINKS = (
  ('C','Coffee'),
  ('B','Beer')
)

FOODS = (
  ('T','Turkey'),
  ('S','Spaghetti')
)

class Item(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)
  def __str__(self):
    return self.name
  def get_absolute_url(self):
    return reverse('items_detail', kwargs={'pk': self.id})

class Friend(models.Model):
  name = models.CharField(max_length=100)
  job = models.CharField(max_length=50)
  description = models.TextField(max_length=250)
  items = models.ManyToManyField(Item)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  def __str__(self):
    return self.name
  def get_absolute_url(self):
    return reverse("friends_detail", kwargs={"friend_id": self.id})
  def ordered_for_today(self):
    return self.order_set.filter(date=date.today()).count() >= len(DRINKS)
  
class Order(models.Model):
  date = models.DateField('Order date')
  drink = models.CharField(
    max_length=1,
    choices=DRINKS,
    default=DRINKS[0][0]
  )
  food = models.CharField(
    max_length=1,
    choices=FOODS,
    default=FOODS[0][0]
  )
  friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
  def __str__(self):
    return f"{self.get_drink_display()} to drink and {self.food()} to eat on {self.date}"
  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Order

class OrderForm(ModelForm):
  class Meta:
    model = Order
    fields = ['date', 'drink', 'food']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from .models import Friend, Item
from .forms import OrderForm

class Friend:
  def __init__(self, name, job, description):
    self.name = name
    self.job = job
    self.description = description

class FriendCreate(LoginRequiredMixin, CreateView):
  model = Friend
  fields = ['name', 'job', 'description']
  success_url = '/friends/'
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class FriendUpdate(LoginRequiredMixin, UpdateView):
  model = Friend
  fields = '__all__'

class FriendDelete(LoginRequiredMixin, DeleteView):
  model = Friend
  success_url = '/friends/'
  
class ItemCreate(LoginRequiredMixin, CreateView):
  model = Item
  fields = '__all__'

class ItemList(LoginRequiredMixin, ListView):
  model = Item

class ItemDetail(LoginRequiredMixin, DetailView):
  model = Item

class ItemUpdate(LoginRequiredMixin, UpdateView):
  model = Item
  fields = ['name', 'color']

class ItemDelete(LoginRequiredMixin, DeleteView):
  model = Item
  success_url = '/items/'

class Home(LoginView):
  template_name = 'home.html'

friends = [
  Friend('Joey', 'doctor/actor', 'Likes girls. Loves to eat.'),
  Friend('Phoebe', 'masseuse', 'In touch with the supernatural.'),
  Friend('Ross', 'paleontologist', 'Great mover. Skilled on the keys'),
  Friend('Rachel', 'fashion designer', 'Mischevious but caring.'),
  Friend('Chandler', 'accountant', 'Dance is my life.'),
  Friend('Monica', 'chef', 'Neat and organized.'),
]

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def friends_index(request):
  friends = Friend.objects.filter(user=request.user)
  return render(request, 'friends/index.html', { 'friends': friends })

@login_required
def friends_detail(request, friend_id):
  friend = Friend.objects.get(id=friend_id)
  items_friend_doesnt_have = Friend.objects.exclude(id__in = friend.items.all().values_list('id'))
  order_form = OrderForm()
  return render(
    request,
    'friends/detail.html',
    { 'friend': friend },
    { 'order_form': order_form },
    { 'items': items_friend_doesnt_have }
  )

@login_required
def add_order(request, friend_id):
  form = OrderForm(request.POST)
  if form.is_valid():
    new_order.friend_id = form.save(commit=False)
    new_order.friend_id = friend_id
    new_order.save()
  return redirect('friends_detail', friend_id=friend_id)

def assoc_item(request, friend_id, item_id):
  Friend.objects.get(id=friend_id).items.add(item_id)
  return redirect('friends_detail', friend_id=friend_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('friends_index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Friend Collector</h1>
<hr />
<p class="page-content">
  I'll be there for you.
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/favicon.png' %}"
  >
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/base.css' %}"
  >
  <title>Friend Collector</title>
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="/">
        <img 
          src="{% static 'images/header-logo.png' %}"
          alt="The Friend Collector Logo"
        >
      </a>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'friends_index' %}">All Friends</a></li>
          <li><a href="{% url 'items_index' %}">All Items</a></li>
          <li><a href="{% url 'friends_create' %}">Add a Friend</a></li>
          <li><a href="{% url 'items_create' %}">Add an Item</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/friends/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/friends/friend-detail.css' %}"
/>
<script defer src="{% static 'js/friend-detail.js' %}"></script>
{% endblock %}

{% block content %}

<section class="friend-container">
  <div class="friend-img">
    <img 
      src="{% static 'images/joey.png' %}" 
      alt="Joey"
    >
  </div>
  <div class="friend-details">
    <h1>{{ friend.name }}</h1>
    <h2>This friend is a {{ friend.job }}</h2>
    <p>{{ friend.description }}</p>
  </div>
</section>
<div class="orders-container">
  <section class="orders">
    <div class="subsection-title">
      <h2>Orders</h2>
      <img 
        src="{% static 'images/joey.png' %}" 
        alt="Joey"
      />
      <img 
        src="{% static 'images/joey.png' %}"
        alt="Joey"
      />
      <img 
        src="{% static 'images/joey.png' %}" 
        alt="Joey"
      />
    </div>
    <h3>Add an Order</h3>
    <form
      action="{% url 'add_order' friend.id %}" 
      method="post" 
      class="subsection-content"
    >
      {% if friend.ordered_for_today %}
        <p class="fed">{{friend.name}} has eaten all their meals for today!</p>
      {% else %}
        <p class="unfed">{{friend.name}} might be hungry!</p>
      {% endif %}
      {% csrf_token %}
      {{ order_form.as_p }}
      <button type="submit" class="btn submit">Add Order</button>
    </form>
    <h3>Past Orders</h3>
    {% if friend.order_set.all.count %}
      <table>
        <thead>
          <tr><th>Date</th><th>Drink</th><th>Food</th></tr>
        </thead>
        <tbody>
          {% for order in friend.order_set.all %}
          <tr>
            <td>{{order.date}}</td>
            <td>{{order.get_drink_display}}</td>
            <td>{{order.get_food_display}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
			<div class="subsection-content">
        <p>{{friend.name}} doesn't have previous orders</p>
      </div>
    {% endif %}
  </section>
  <section class="items">
    <div class="subsection-title">
      <h2>Items</h2>
      <img src="{% static 'images/joey.png' %}" alt="Joey" />
      <img src="{% static 'images/joey.png' %}" alt="Joey" />
      <img src="{% static 'images/joey.png' %}" alt="Joey" />
    </div>
    <h3>{{ friend.name }}'s items</h3>
    <div class="subsection-content">
      {% if friend.items.count %}
        {% for item in friend.items.all %}
          <div class="item-container">
            <div 
              class="color-block"
              style="background-color: {{ item.color }}"
            ></div>
            <a href="{% url 'items_detail' item.id %}">
              <p>A {{ item.color }} {{ item.name }}</p>
            </a>
          </div>
        {% endfor %}
      {% else %}
        <p class="no-items">{{friend.name}} doesn't have any items 😞</p>
      {% endif %}
    </div>
    <h3>Available Items</h3>
    <div class="subsection-content">
      {% if items.count %}
        {% for item in items.all %}
          <div class="item-container">
            <div 
              class="color-block"
              style="background-color: {{ item.color }}"
            ></div>
            <a href="{% url 'items_detail' item.id %}">
              <p>A {{ item.color }} {{ item.name }}</p>
            </a>
            <form action="{% url 'assoc_item' friend.id item.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn submit">Give item</button>
            </form>
          </div>
        {% endfor %}
      {% else %}
        <p class="all-items">
          {{friend.name}} already has all the available items 🥳
        </p>
      {% endif %}
    </div>
  </section>
</div>

{% endblock %}

main_app/templates/friends/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/friends/friend-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Friend List</h1>
  <img src="{% static 'images/joey.png' %}" alt="Joey" />
  <img src="{% static 'images/rachel.png' %}" alt="Rachel" />
  <img src="{% static 'images/ross.png' %}" alt="Ross" />
  <img src="{% static 'images/monica.png' %}" alt="Monica" />
  <img src="{% static 'images/phoebe.png' %}" alt="Phoebe" />
  <img src="{% static 'images/chandler.png' %}" alt="Chandler" />
</section>

<section class="card-container">
  {% for friend in friends %}
    <div class="card">
      <a href='{% url 'friends_detail' friend.id %}'
        <div class="card-content">
          <div class="card-img-container">
            <img 
              src="{% static 'images/joey.png' %}" 
              alt="Joey"
            >
          </div>
          <h2 class="card-title">{{ friend.name }}</h2>
          <p>A {{ friend.name }} is a {{ friend.job }}</p>
          <p><small>{{ friend.description }}</small></p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="friend-container">
    <img src="{% static 'images/favicon.png' %}" alt="The Friend Collector Friend" />
  </div>
  <img 
    src="{% static 'images/header-logo.png' %}" 
    alt="Text reads: Freind Collector"
  />
</section>
{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/friend_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Friend?</h1>
  <img src="{% static 'images/joey' %}" alt="Joey"/>
</div>
<h2>Are you sure you want to delete {{ friend.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'friends_detail' friend.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/friend_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

	{% if friend %}
		<h1>Edit {{ friend.name }}</h1>
	{% else %}
		<h1>Add a Friend</h1>
	{% endif %}

<div class="page-header">
  <h1>Add a Friend</h1>
  <img src="{% static 'images/joey.svg' %}" alt="Joey"/>
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Item?</h1>
  <img src="{% static 'images/joey.png' %}" alt="Joey"/>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'items_detail' item.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/item_detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/items/item-detail.css' %}"
/>
{% endblock %}

{% block content %}
  
<div class="card" style="border-color: {{ item.color }}">
  <div class="card-bg" style="background-color: {{ item.color }}"></div>
  <div class="card-content">
    <h2>{{ item.name }}</h2>
    <p>A {{ item.color }} item</p>
  </div>
</div>
<a href="{% url 'items_update' item.id %}" class="btn warn">Edit</a>
<a href="{% url 'items_delete' item.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}
<div class="page-header">
  {% if object %}
    <h1>Edit {{object.name}}</h1>
  {% else %}
    <h1>Add an Item</h1>
  {% endif %}
  <img src="{% static 'images/joey' %}" alt="Joey"/>
</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/item_list.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/items/item-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>All Friend Items</h1>
  <img src="{% static 'images/joey.png' %}" alt="Joey" />
  <img src="{% static 'images/joey.png' %}" alt="Joey" />
  <img src="{% static 'images/joey.png' %}" alt="Joey" />
  <img src="{% static 'images/joey.png' %}" alt="Joey" />
</section>

<section class="card-container">
  {% for item in item_list %}
  <div class="card" style="border-color: {{ item.color }}">
    <div class="card-bg" style="background-color: {{ item.color }}"></div>
    <a href="{% url 'items_detail' item.id %}">
      <div class="card-content">
        <h2>{{ item.name }}</h2>
        <p>A {{ item.color }} item</p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/joey.png' %}" alt="Joey"/>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}